### ISSUE TITLE
Disable crumb per route

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/crumb#42] opened 2015-01-23 11:22 UTC
Hi,

Is there a way to disable the crumb through the route configuration?

In the documentation I see that we can do like this:
~~~javascript
options: {
    restful: true,
    cookieOptions: {
        ttl: 86400000
    },
    skip: function(request, reply) {
        // to disable it for the save-email method
        if (request.path === 'save-email') {
            return true;
        }
    }
}
~~~

This mean that we should describe all the routes which we want to "decrumbialise" during the plugin registration. Am I right?

**Comment by stongo** [comment] 2015-01-28 13:47
Hi! This is a duplicate of https://github.com/hapijs/crumb/issues/32

**Closed by stongo** 2015-01-28 13:47 UTC
