### ISSUE TITLE
autoGenerate=false not working as expected

### ISSUE THREAD

**Issue by jamtay** [hapijs/crumb#108] opened 2018-01-16 15:32 UTC
Tried setting autoGenerate to false but when this happened the crumb was never checked (Could update the hidden form field with any value and not get a 403 forbidden) 

I had already globally set the crumbOptions but to fix this I also had to add an empty object for `config.plugins.crumb` for every route.  With this changed autoGenerate worked as I expected but I am confused about why I have to add `config.plugins.crumb` to every route to fix this?

**Comment by spanditcaa** [comment] 2018-04-26 04:04
This appears to be a duplicate of #94 -- @jspath is the PR you referenced in pageamedia a fix, or workaround for crumb?

**Comment by jspath** [comment] 2018-04-26 15:03
It's a "fix" that works for us against version 7.0.0 of crumb.

We are old an older version of hapi right now and cannot upgrade to newest crumb.

**Comment by hueniverse** [comment] 2019-04-20 05:51
I am assuming this is not an issue anymore since it's been a year without progress on this. Since hapi v16 is no longer supported, I am closing it as the fix will not be backported. If you still need hapi v16 support including this module, please contact me for information about commercial support.

**Closed by hueniverse** 2019-04-20 05:51 UTC
Labels: bug, help wanted
